Repository Rebilly/RebillyAPI, pull requests merged in 2019-01, with the labels that each got.

#572 Add Transaction Request API
  spec/components/requestBodies/TransactionRequest.yaml
  spec/components/schemas/Transactions/Transaction.yaml
  spec/components/schemas/Transactions/TransactionRequest.yaml
  spec/openapi.yaml
  spec/paths/payments.yaml
  spec/paths/payments@{id}.yaml
  spec/paths/queue@payments.yaml
  spec/paths/queue@payments@{id}.yaml
  spec/paths/transactions.yaml
Labels: enhancement

#580 Fix Customer Authentication API spec
  spec/components/schemas/AuthenticationToken.yaml
  spec/components/schemas/Credential.yaml
  spec/components/schemas/ResetPasswordToken.yaml
Labels: bug

#584 Move to external description and update font
  spec/openapi.yaml
  spec/paths/files.yaml
  spec/paths/tokens.yaml
  web/description.md
  web/index.html
  web/redoc-config.yaml
Labels: enhancement

#597 Update getting started guide to include FramePay
  web/description.md
Labels: enhancement

#605 Add getting started videos
  web/description.md
Labels: enhancement

#544 Add tags endpoints
  spec/components/parameters/customerId.yaml
  spec/components/parameters/tag.yaml
  spec/components/requestBodies/Tag.yaml
  spec/components/schemas/Customer.yaml
  spec/components/schemas/InvalidError.yaml
  spec/components/schemas/Tags/Tag.yaml
  spec/openapi.yaml
  spec/paths/tags.yaml
  spec/paths/tags@{tag}.yaml
  spec/paths/tags@{tag}@customers.yaml
  spec/paths/tags@{tag}@customers@{customerId}.yaml
Labels: help wanted
